import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '../globals.css';
import { SidebarInset, SidebarProvider } from '@/components/ui/sidebar';
import { AppSidebar } from '@/components/app-sidebar';
import AppTopBar from '@/components/app-topbar';
import { fetchApi } from './utils/api';
import { IUserInfo } from './shared/types';
import { UserInfoProvider } from './context/UserInfoContext';
import { cookies } from 'next/headers';

const geistSans = localFont({
  src: '../fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: '../fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const jwtToken = (await cookies()).get('jwt')?.value ?? '';

  const UserInfo = await fetchApi<IUserInfo>('/auth/info', {
    headers: {
      Authorization: `Bearer ${jwtToken}`,
    },
  });
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserInfoProvider UserInfo={UserInfo}>
          <SidebarProvider>
            <AppSidebar />
            <SidebarInset>
              <AppTopBar />
              {children}
            </SidebarInset>
          </SidebarProvider>
        </UserInfoProvider>
      </body>
    </html>
  );
}
